// <auto-generated />
using ASPNetCore.API.Boilerplate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPNetCore.API.Boilerplate.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20180221144210_CreateCompanyTable")]
    partial class CreateCompanyTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNetCore.API.Boilerplate.Models.CompanyModel", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ASPNetCore.API.Boilerplate.Models.EmployeeModel", b =>
                {
                    b.Property<string>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CompanyModelCompanyID");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("EmployeeID");

                    b.HasIndex("CompanyModelCompanyID");

                    b.ToTable("EmployeeModel");
                });

            modelBuilder.Entity("ASPNetCore.API.Boilerplate.Models.EmployeeModel", b =>
                {
                    b.HasOne("ASPNetCore.API.Boilerplate.Models.CompanyModel")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyModelCompanyID");
                });
#pragma warning restore 612, 618
        }
    }
}
